# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_date', models.DateTimeField(verbose_name='date requested')),
                ('iden', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('lon', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('population', models.CharField(max_length=100)),
                ('cod', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('cnt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_text', models.CharField(max_length=1200)),
                ('forecast_date', models.DateTimeField(verbose_name='forecast date')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.City')),
            ],
        ),
    ]
