# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OWM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_date', models.DateTimeField(verbose_name='request date')),
                ('iden', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('coord_lon', models.CharField(max_length=100)),
                ('coord_lat', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('population', models.CharField(max_length=100)),
                ('sys_population', models.CharField(max_length=100)),
                ('cod', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('cnt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OWMForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_text', models.CharField(max_length=1200)),
                ('owm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.OWM')),
            ],
        ),
        migrations.RemoveField(
            model_name='forecast',
            name='city',
        ),
        migrations.RemoveField(
            model_name='city',
            name='cnt',
        ),
        migrations.RemoveField(
            model_name='city',
            name='cod',
        ),
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='city',
            name='iden',
        ),
        migrations.RemoveField(
            model_name='city',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='city',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='city',
            name='message',
        ),
        migrations.RemoveField(
            model_name='city',
            name='population',
        ),
        migrations.RemoveField(
            model_name='city',
            name='req_date',
        ),
        migrations.AddField(
            model_name='city',
            name='ds_owm',
            field=models.URLField(default='init ds'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Forecast',
        ),
    ]
