# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_owm_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='turn',
            field=models.BooleanField(default=True),
        ),
    ]
