# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_auto_20170225_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yahoo',
            name='yql_resp_text',
            field=models.CharField(max_length=3000),
        ),
    ]
