# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_auto_20170301_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yahooforecast',
            name='owm',
        ),
        migrations.AddField(
            model_name='yahooforecast',
            name='yahoo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='weather.Yahoo'),
            preserve_default=False,
        ),
    ]
