# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_auto_20170301_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='ds_yahoo',
            field=models.URLField(max_length=250),
        ),
    ]
